// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pushk1nn/netwatch/ent/connections"
)

// ConnectionsCreate is the builder for creating a Connections entity.
type ConnectionsCreate struct {
	config
	mutation *ConnectionsMutation
	hooks    []Hook
}

// SetTime sets the "time" field.
func (_c *ConnectionsCreate) SetTime(v time.Time) *ConnectionsCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetUnixTime sets the "unix_time" field.
func (_c *ConnectionsCreate) SetUnixTime(v int64) *ConnectionsCreate {
	_c.mutation.SetUnixTime(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ConnectionsCreate) SetType(v string) *ConnectionsCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *ConnectionsCreate) SetIP(v string) *ConnectionsCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ConnectionsCreate) SetID(v uuid.UUID) *ConnectionsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConnectionsCreate) SetNillableID(v *uuid.UUID) *ConnectionsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ConnectionsMutation object of the builder.
func (_c *ConnectionsCreate) Mutation() *ConnectionsMutation {
	return _c.mutation
}

// Save creates the Connections in the database.
func (_c *ConnectionsCreate) Save(ctx context.Context) (*Connections, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConnectionsCreate) SaveX(ctx context.Context) *Connections {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConnectionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConnectionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConnectionsCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := connections.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConnectionsCreate) check() error {
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Connections.time"`)}
	}
	if _, ok := _c.mutation.UnixTime(); !ok {
		return &ValidationError{Name: "unix_time", err: errors.New(`ent: missing required field "Connections.unix_time"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Connections.type"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Connections.ip"`)}
	}
	return nil
}

func (_c *ConnectionsCreate) sqlSave(ctx context.Context) (*Connections, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConnectionsCreate) createSpec() (*Connections, *sqlgraph.CreateSpec) {
	var (
		_node = &Connections{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(connections.Table, sqlgraph.NewFieldSpec(connections.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(connections.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.UnixTime(); ok {
		_spec.SetField(connections.FieldUnixTime, field.TypeInt64, value)
		_node.UnixTime = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(connections.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(connections.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	return _node, _spec
}

// ConnectionsCreateBulk is the builder for creating many Connections entities in bulk.
type ConnectionsCreateBulk struct {
	config
	err      error
	builders []*ConnectionsCreate
}

// Save creates the Connections entities in the database.
func (_c *ConnectionsCreateBulk) Save(ctx context.Context) ([]*Connections, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Connections, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConnectionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConnectionsCreateBulk) SaveX(ctx context.Context) []*Connections {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConnectionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConnectionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
