// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pushk1nn/netwatch/ent/connections"
)

// Connections is the model entity for the Connections schema.
type Connections struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Unique ID associated with individual log
	EventID string `json:"event_id,omitempty"`
	// Time at which event occurred
	Time time.Time `json:"time,omitempty"`
	// Event type (connect, disconnect)
	Type string `json:"type,omitempty"`
	// IP from which a connection is coming from
	IP           string `json:"ip,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Connections) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case connections.FieldID:
			values[i] = new(sql.NullInt64)
		case connections.FieldEventID, connections.FieldType, connections.FieldIP:
			values[i] = new(sql.NullString)
		case connections.FieldTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Connections fields.
func (_m *Connections) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case connections.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case connections.FieldEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.String
			}
		case connections.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = value.Time
			}
		case connections.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case connections.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Connections.
// This includes values selected through modifiers, order, etc.
func (_m *Connections) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Connections.
// Note that you need to call Connections.Unwrap() before calling this method if this Connections
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Connections) Update() *ConnectionsUpdateOne {
	return NewConnectionsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Connections entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Connections) Unwrap() *Connections {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Connections is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Connections) String() string {
	var builder strings.Builder
	builder.WriteString("Connections(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(_m.EventID)
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(_m.Time.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteByte(')')
	return builder.String()
}

// ConnectionsSlice is a parsable slice of Connections.
type ConnectionsSlice []*Connections
