// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pushk1nn/netwatch/ent/connections"
	"github.com/pushk1nn/netwatch/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeConnections = "Connections"
)

// ConnectionsMutation represents an operation that mutates the Connections nodes in the graph.
type ConnectionsMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	time          *time.Time
	unix_time     *int64
	addunix_time  *int64
	_type         *string
	ip            *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Connections, error)
	predicates    []predicate.Connections
}

var _ ent.Mutation = (*ConnectionsMutation)(nil)

// connectionsOption allows management of the mutation configuration using functional options.
type connectionsOption func(*ConnectionsMutation)

// newConnectionsMutation creates new mutation for the Connections entity.
func newConnectionsMutation(c config, op Op, opts ...connectionsOption) *ConnectionsMutation {
	m := &ConnectionsMutation{
		config:        c,
		op:            op,
		typ:           TypeConnections,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withConnectionsID sets the ID field of the mutation.
func withConnectionsID(id uuid.UUID) connectionsOption {
	return func(m *ConnectionsMutation) {
		var (
			err   error
			once  sync.Once
			value *Connections
		)
		m.oldValue = func(ctx context.Context) (*Connections, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Connections.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withConnections sets the old Connections of the mutation.
func withConnections(node *Connections) connectionsOption {
	return func(m *ConnectionsMutation) {
		m.oldValue = func(context.Context) (*Connections, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ConnectionsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ConnectionsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Connections entities.
func (m *ConnectionsMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ConnectionsMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ConnectionsMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Connections.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTime sets the "time" field.
func (m *ConnectionsMutation) SetTime(t time.Time) {
	m.time = &t
}

// Time returns the value of the "time" field in the mutation.
func (m *ConnectionsMutation) Time() (r time.Time, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the Connections entity.
// If the Connections object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionsMutation) OldTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *ConnectionsMutation) ResetTime() {
	m.time = nil
}

// SetUnixTime sets the "unix_time" field.
func (m *ConnectionsMutation) SetUnixTime(i int64) {
	m.unix_time = &i
	m.addunix_time = nil
}

// UnixTime returns the value of the "unix_time" field in the mutation.
func (m *ConnectionsMutation) UnixTime() (r int64, exists bool) {
	v := m.unix_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUnixTime returns the old "unix_time" field's value of the Connections entity.
// If the Connections object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionsMutation) OldUnixTime(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUnixTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUnixTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUnixTime: %w", err)
	}
	return oldValue.UnixTime, nil
}

// AddUnixTime adds i to the "unix_time" field.
func (m *ConnectionsMutation) AddUnixTime(i int64) {
	if m.addunix_time != nil {
		*m.addunix_time += i
	} else {
		m.addunix_time = &i
	}
}

// AddedUnixTime returns the value that was added to the "unix_time" field in this mutation.
func (m *ConnectionsMutation) AddedUnixTime() (r int64, exists bool) {
	v := m.addunix_time
	if v == nil {
		return
	}
	return *v, true
}

// ResetUnixTime resets all changes to the "unix_time" field.
func (m *ConnectionsMutation) ResetUnixTime() {
	m.unix_time = nil
	m.addunix_time = nil
}

// SetType sets the "type" field.
func (m *ConnectionsMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *ConnectionsMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Connections entity.
// If the Connections object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionsMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *ConnectionsMutation) ResetType() {
	m._type = nil
}

// SetIP sets the "ip" field.
func (m *ConnectionsMutation) SetIP(s string) {
	m.ip = &s
}

// IP returns the value of the "ip" field in the mutation.
func (m *ConnectionsMutation) IP() (r string, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the Connections entity.
// If the Connections object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionsMutation) OldIP(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// ResetIP resets all changes to the "ip" field.
func (m *ConnectionsMutation) ResetIP() {
	m.ip = nil
}

// Where appends a list predicates to the ConnectionsMutation builder.
func (m *ConnectionsMutation) Where(ps ...predicate.Connections) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ConnectionsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ConnectionsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Connections, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ConnectionsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ConnectionsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Connections).
func (m *ConnectionsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ConnectionsMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.time != nil {
		fields = append(fields, connections.FieldTime)
	}
	if m.unix_time != nil {
		fields = append(fields, connections.FieldUnixTime)
	}
	if m._type != nil {
		fields = append(fields, connections.FieldType)
	}
	if m.ip != nil {
		fields = append(fields, connections.FieldIP)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ConnectionsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case connections.FieldTime:
		return m.Time()
	case connections.FieldUnixTime:
		return m.UnixTime()
	case connections.FieldType:
		return m.GetType()
	case connections.FieldIP:
		return m.IP()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ConnectionsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case connections.FieldTime:
		return m.OldTime(ctx)
	case connections.FieldUnixTime:
		return m.OldUnixTime(ctx)
	case connections.FieldType:
		return m.OldType(ctx)
	case connections.FieldIP:
		return m.OldIP(ctx)
	}
	return nil, fmt.Errorf("unknown Connections field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConnectionsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case connections.FieldTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	case connections.FieldUnixTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUnixTime(v)
		return nil
	case connections.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case connections.FieldIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	}
	return fmt.Errorf("unknown Connections field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ConnectionsMutation) AddedFields() []string {
	var fields []string
	if m.addunix_time != nil {
		fields = append(fields, connections.FieldUnixTime)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ConnectionsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case connections.FieldUnixTime:
		return m.AddedUnixTime()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConnectionsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case connections.FieldUnixTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUnixTime(v)
		return nil
	}
	return fmt.Errorf("unknown Connections numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ConnectionsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ConnectionsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ConnectionsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Connections nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ConnectionsMutation) ResetField(name string) error {
	switch name {
	case connections.FieldTime:
		m.ResetTime()
		return nil
	case connections.FieldUnixTime:
		m.ResetUnixTime()
		return nil
	case connections.FieldType:
		m.ResetType()
		return nil
	case connections.FieldIP:
		m.ResetIP()
		return nil
	}
	return fmt.Errorf("unknown Connections field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ConnectionsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ConnectionsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ConnectionsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ConnectionsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ConnectionsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ConnectionsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ConnectionsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Connections unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ConnectionsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Connections edge %s", name)
}
