// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connections is the predicate function for connections builders.
type Connections func(*sql.Selector)
