// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pushk1nn/netwatch/ent/connections"
	"github.com/pushk1nn/netwatch/ent/predicate"
)

// ConnectionsUpdate is the builder for updating Connections entities.
type ConnectionsUpdate struct {
	config
	hooks    []Hook
	mutation *ConnectionsMutation
}

// Where appends a list predicates to the ConnectionsUpdate builder.
func (_u *ConnectionsUpdate) Where(ps ...predicate.Connections) *ConnectionsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTime sets the "time" field.
func (_u *ConnectionsUpdate) SetTime(v time.Time) *ConnectionsUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *ConnectionsUpdate) SetNillableTime(v *time.Time) *ConnectionsUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetUnixTime sets the "unix_time" field.
func (_u *ConnectionsUpdate) SetUnixTime(v int64) *ConnectionsUpdate {
	_u.mutation.ResetUnixTime()
	_u.mutation.SetUnixTime(v)
	return _u
}

// SetNillableUnixTime sets the "unix_time" field if the given value is not nil.
func (_u *ConnectionsUpdate) SetNillableUnixTime(v *int64) *ConnectionsUpdate {
	if v != nil {
		_u.SetUnixTime(*v)
	}
	return _u
}

// AddUnixTime adds value to the "unix_time" field.
func (_u *ConnectionsUpdate) AddUnixTime(v int64) *ConnectionsUpdate {
	_u.mutation.AddUnixTime(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConnectionsUpdate) SetType(v string) *ConnectionsUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConnectionsUpdate) SetNillableType(v *string) *ConnectionsUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ConnectionsUpdate) SetIP(v string) *ConnectionsUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ConnectionsUpdate) SetNillableIP(v *string) *ConnectionsUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// Mutation returns the ConnectionsMutation object of the builder.
func (_u *ConnectionsUpdate) Mutation() *ConnectionsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConnectionsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConnectionsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConnectionsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConnectionsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConnectionsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(connections.Table, connections.Columns, sqlgraph.NewFieldSpec(connections.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(connections.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnixTime(); ok {
		_spec.SetField(connections.FieldUnixTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnixTime(); ok {
		_spec.AddField(connections.FieldUnixTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(connections.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(connections.FieldIP, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connections.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConnectionsUpdateOne is the builder for updating a single Connections entity.
type ConnectionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConnectionsMutation
}

// SetTime sets the "time" field.
func (_u *ConnectionsUpdateOne) SetTime(v time.Time) *ConnectionsUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *ConnectionsUpdateOne) SetNillableTime(v *time.Time) *ConnectionsUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetUnixTime sets the "unix_time" field.
func (_u *ConnectionsUpdateOne) SetUnixTime(v int64) *ConnectionsUpdateOne {
	_u.mutation.ResetUnixTime()
	_u.mutation.SetUnixTime(v)
	return _u
}

// SetNillableUnixTime sets the "unix_time" field if the given value is not nil.
func (_u *ConnectionsUpdateOne) SetNillableUnixTime(v *int64) *ConnectionsUpdateOne {
	if v != nil {
		_u.SetUnixTime(*v)
	}
	return _u
}

// AddUnixTime adds value to the "unix_time" field.
func (_u *ConnectionsUpdateOne) AddUnixTime(v int64) *ConnectionsUpdateOne {
	_u.mutation.AddUnixTime(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConnectionsUpdateOne) SetType(v string) *ConnectionsUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConnectionsUpdateOne) SetNillableType(v *string) *ConnectionsUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ConnectionsUpdateOne) SetIP(v string) *ConnectionsUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ConnectionsUpdateOne) SetNillableIP(v *string) *ConnectionsUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// Mutation returns the ConnectionsMutation object of the builder.
func (_u *ConnectionsUpdateOne) Mutation() *ConnectionsMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConnectionsUpdate builder.
func (_u *ConnectionsUpdateOne) Where(ps ...predicate.Connections) *ConnectionsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConnectionsUpdateOne) Select(field string, fields ...string) *ConnectionsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Connections entity.
func (_u *ConnectionsUpdateOne) Save(ctx context.Context) (*Connections, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConnectionsUpdateOne) SaveX(ctx context.Context) *Connections {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConnectionsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConnectionsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ConnectionsUpdateOne) sqlSave(ctx context.Context) (_node *Connections, err error) {
	_spec := sqlgraph.NewUpdateSpec(connections.Table, connections.Columns, sqlgraph.NewFieldSpec(connections.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Connections.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, connections.FieldID)
		for _, f := range fields {
			if !connections.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != connections.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(connections.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnixTime(); ok {
		_spec.SetField(connections.FieldUnixTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnixTime(); ok {
		_spec.AddField(connections.FieldUnixTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(connections.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(connections.FieldIP, field.TypeString, value)
	}
	_node = &Connections{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connections.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
