// Code generated by ent, DO NOT EDIT.

package connections

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pushk1nn/netwatch/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Connections {
	return predicate.Connections(sql.FieldLTE(FieldID, id))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldTime, v))
}

// UnixTime applies equality check predicate on the "unix_time" field. It's identical to UnixTimeEQ.
func UnixTime(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldUnixTime, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldType, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldIP, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v time.Time) predicate.Connections {
	return predicate.Connections(sql.FieldLTE(FieldTime, v))
}

// UnixTimeEQ applies the EQ predicate on the "unix_time" field.
func UnixTimeEQ(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldUnixTime, v))
}

// UnixTimeNEQ applies the NEQ predicate on the "unix_time" field.
func UnixTimeNEQ(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldNEQ(FieldUnixTime, v))
}

// UnixTimeIn applies the In predicate on the "unix_time" field.
func UnixTimeIn(vs ...int64) predicate.Connections {
	return predicate.Connections(sql.FieldIn(FieldUnixTime, vs...))
}

// UnixTimeNotIn applies the NotIn predicate on the "unix_time" field.
func UnixTimeNotIn(vs ...int64) predicate.Connections {
	return predicate.Connections(sql.FieldNotIn(FieldUnixTime, vs...))
}

// UnixTimeGT applies the GT predicate on the "unix_time" field.
func UnixTimeGT(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldGT(FieldUnixTime, v))
}

// UnixTimeGTE applies the GTE predicate on the "unix_time" field.
func UnixTimeGTE(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldGTE(FieldUnixTime, v))
}

// UnixTimeLT applies the LT predicate on the "unix_time" field.
func UnixTimeLT(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldLT(FieldUnixTime, v))
}

// UnixTimeLTE applies the LTE predicate on the "unix_time" field.
func UnixTimeLTE(v int64) predicate.Connections {
	return predicate.Connections(sql.FieldLTE(FieldUnixTime, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Connections {
	return predicate.Connections(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Connections {
	return predicate.Connections(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Connections {
	return predicate.Connections(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Connections {
	return predicate.Connections(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Connections {
	return predicate.Connections(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Connections {
	return predicate.Connections(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Connections {
	return predicate.Connections(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Connections {
	return predicate.Connections(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Connections {
	return predicate.Connections(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Connections {
	return predicate.Connections(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Connections {
	return predicate.Connections(sql.FieldContainsFold(FieldType, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Connections {
	return predicate.Connections(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Connections {
	return predicate.Connections(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Connections {
	return predicate.Connections(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Connections {
	return predicate.Connections(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Connections {
	return predicate.Connections(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Connections {
	return predicate.Connections(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Connections {
	return predicate.Connections(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Connections {
	return predicate.Connections(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Connections {
	return predicate.Connections(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Connections {
	return predicate.Connections(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Connections {
	return predicate.Connections(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Connections {
	return predicate.Connections(sql.FieldContainsFold(FieldIP, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Connections) predicate.Connections {
	return predicate.Connections(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Connections) predicate.Connections {
	return predicate.Connections(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Connections) predicate.Connections {
	return predicate.Connections(sql.NotPredicates(p))
}
